; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; Ці два рядки часто вирішують проблему "пустого терміналу"
;monitor_dtr = 0
;monitor_rts = 0
;monitor_filters = send_on_enter, time

; --- НАЛАШТУВАННЯ OTA ---
;upload_protocol = espota
;upload_port = 192.168.179.209

build_flags = 
    -D CORE_DEBUG_LEVEL=1
 ;   -D ARDUINO_USB_MODE=1
  ;  -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit NeoPixel @ ^1.12.0

platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#master

